# Generated by Django 3.1.7 on 2021-04-18 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210418_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Time')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('venue', models.CharField(max_length=30, verbose_name='Venue')),
                ('status', models.CharField(choices=[('1', 'upcoming'), ('2', 'incipient'), ('3', 'completed'), ('4', 'cancelled')], default=1, max_length=15, verbose_name='Status')),
                ('created_by', models.CharField(max_length=30)),
                ('clients', models.ManyToManyField(to='users.Client')),
                ('troupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.troupe')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_name', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointment')),
            ],
        ),
    ]
