# Generated by Django 3.1.7 on 2021-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='emoji_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
