# Generated by Django 3.1.7 on 2021-04-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rating_emoji_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='emoji_url',
        ),
    ]
