# Generated by Django 2.2.4 on 2019-08-21 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_name', models.CharField(max_length=128, verbose_name='Guardian Name')),
                ('contact_email', models.EmailField(max_length=254, unique=True, verbose_name='Guardian Email')),
                ('contact_number', models.CharField(max_length=16, verbose_name='Contact Person Number')),
            ],
        ),
        migrations.CreateModel(
            name='Troupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('max_capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_clown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_troupe_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TroupeLeader',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('troupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Troupe')),
            ],
        ),
        migrations.CreateModel(
            name='Clown',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rank', models.IntegerField()),
                ('troupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Troupe')),
            ],
        ),
    ]
